### ISSUE TITLE
Ajouter des boutons de partage sur les réseaux sociaux aux pages d'événements et de groupes

### ISSUE THREAD

**Issue by aktiur** [lafranceinsoumise/actionpopulaire.fr#13]
## Objectif

Ajouter des boutons "Partager" pour les réseaux sociaux (au moins Twitter et Facebook) sur les pages présentant les événements et les groupes d'appui, pour permettre le partage en un clic.

## Compétences nécessaires

* HTML
* Réseaux sociaux
* Un peu de Django

## Où intervenir

* `front/templates/front/events/details.html`
* `front/templates/front/groups/details.html`

**Comment by nilsine** [comment]
Peut-on utiliser des services type addthis.com ?

**Comment by guilro** [comment]
Cela peut passer par un plugin, mais ne doit pas faire fuiter de données personnelles vers un service tiers.
