### ISSUE TITLE
Ajouter une fonctionnalité de création d'un événement à partir d'un événement Facebook

### ISSUE THREAD

**Issue by aktiur** [lafranceinsoumise/actionpopulaire.fr#14]
## Objectif

Dans le but de faciliter pour les utilisateurs la création d'événements sur la plateforme pour les utilisateurs qui souhaitent de toute façon créer le même événement sur Facebook, il faudrait permettre de pré-remplir le formulaire de création d'événement à partir de l'événement Facebook.

## Compétences nécessaires

* javascript
* html
* Django
* Un peu de Python ?

**Comment by diablade** [comment]
ca peux se faire en pure javascript via une fonction ajax et l'api facebook 
il suffit de créer une application facebook et de la lié à l'ajax 

https://developers.facebook.com/docs/graph-api/reference/event

et ensuite faire un travail dans le dom html et préremplir les champs concerné recu
et laisser l'utilisateur verifier et valider

**Comment by guilro** [comment]
si ça te tente d'essayer, go :) !

**Comment by diablade** [comment]
le seul truc c'est qu'il sera necessaire d'avoir la clef token en public visible dans le JS 
sauf si on fait l'appel depuis le back django (qui lui aura le token en privé) et qui remonte en ajax au front

**Comment by diablade** [comment]
ca me tente bien oui mais j vais pas créer moi l'appli facebook à mon compte par contre faut que ca soit l'un d'entre vous

**Comment by guilro** [comment]
Ce type d'identifiant doit de toute façon être en paramètre et ne pas être
commit avec le code. Il faire que tu te crée ton appli de test pour
développer, et nous créons notre appli de production pour déployer, mais
nous n'allons pas échanger les identifiants.

**Comment by diablade** [comment]
justement si le token ne doit pas etre visible dans le JS, alors il faudrai faire une route public à me donner pour que vous appelez vous en privé depuis django à l'api facebook

**Comment by guilro** [comment]
Elle n'existe pas, mais tu peux la créer =) ! Au passage elle ne doit pas être totalement publique. Il faudrait au moins une vérification CSRF.
