### ISSUE TITLE
Bouton "Copier le mail" confusant

### ISSUE THREAD

**Issue by NicolasDumoulin** [lafranceinsoumise/actionpopulaire.fr#144]
Lorsque quelqu'un rejoint un groupe, on reçoit une notification avec deux actions possible : "Copier le mail" et "C'est fait".
Le bouton "Copier le mail" n'est pas très explicite pour tout le monde apparemment.
Suggestion : Ça serait peut-être plus clair en mettant sur le  bouton une icône "copier" et en y collant un champ texte désactivé affichant l'adresse mail.

**Comment by jillro** [comment]
Bonjour ! Merci du retour. Vous êtes plusieurs à l'avoir fait et on va donc modifier ça :) Pour ce type de remontée sinon, c'est mieux de passer par le formulaire https://actionpopulaire.fr/formulaires/votre-avis/ !
